# Generated by Django 6.1.1 on 2026-10-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("especie", models.CharField(max_length=50)),
                ("edad", models.IntegerField()),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("proceso", "En proceso de adopción"),
                            ("adoptado", "Adoptado"),
                        ],
                        default="proceso",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
